apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sdk-auto
  namespace: originx
  labels:
    app: sdk-auto
spec:
  selector:
    matchLabels:
      app: sdk-auto
  template:
    metadata:
      labels:
        app: sdk-auto
    spec:
      hostPID: true
      volumes:
        - name: sdk-auto-config
          configMap:
            name: sdk-auto-config
      containers:
        - name: sdk-auto
          image: sdk-auto:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KINDLING_WRITE_TRACE
              value: 'false'
          ports:
            - name: http
              containerPort: 9502
              protocol: TCP
          volumeMounts:
            - name: sdk-auto-config
              mountPath: /app/sdk-auto.yml
              subPath: sdk-auto.yml
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: sdk-auto-svc
  namespace: originx
  labels:
    app: sdk-auto
spec:
  type: ClusterIP
  selector:
    app: sdk-auto
  ports:
  - name: http
    port: 9502
    protocol: TCP
    targetPort: 9502

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-auto-config
  namespace: originx
data:
  sdk-auto.yml: |
    auto:
      port: 9502
      scan_interval: 30
      trace_api: jaeger.default:4318
      black_list:
        go:
          alloy:
            - alloy
          apisix:
            - apisix-ingress-*
          calico:
            - calico-node
            - kube-controller*
          chaos:
            - chaos-*
            - logserver
          containerd:
            - containerd*
            - image-cri-shim
            - registry
          deepflow-ce:
            - deepflow-server
            - grafana
            - gpx_*
          docker:
            - docker*
            - runc
            - runc:*
          elastic:
            - apm-server
            - elastic-operato*
          flannel:
            - flanneld
          flagd:
            - flagd-build
          go:
            - dlv
            - gopls
          ingress-nginx:
            - nginx-ingress-c*
          jaegertracing:
            - agent-linux
            - all-in-one-linu*
          k8s:
            - coredns
            - etcd
            - kubectl
            - kubelet
            - kube-*
          kind:
            - kindnetd
            - local-path-prov*
          kindling:
            - camera-apm-adap*
            - camera-receiver
            - management
            - metadata-provid*
            - meta-agent
            - originx-gc-agen*
            - originx-sdk-aut*
            - otel-go-instrum*
            - pinger
            - node-agent
            - portal
            - root-cause-infe*
            - originx-apo-bac*
          kubeskoop:
            - inspector
          lvs:
            - lvscare
          metrics-server:
            - metrics-server
          odigos:
            - app
            - odiglet
            - odigosotelcol
          openebs:
            - exporter
            - ndm
            - ndo
            - provisioner-loc*
          opentelemetry:
            - otelcol-contrib
            - otelcol
          olm:
            - catalog
            - olm
          prometheus:
            - node_exporter
            - operator
            - prometheus
            - prometheus-conf*
          radondb:
            - xenon
          victoriametrics:
            - victoria-metric*
            - vmagent-prod
            - vmalert-prod
        java:
          skywalking:
            - "*org.apache.skywalking.oap.server.starter.OAPServerStartUp"
            - "*org.apache.skywalking.oap.server.webapp.ApplicationStartUp"
            - "*skywalking-webapp.jar"
          es:
            - "*org.elasticsearch.bootstrap.Elasticsearch"
            - "*/kindling/apm-agent-attach-cli*"
          zookeeper:
            - "*org.apache.zookeeper.server.quorum.QuorumPeerMain"
          nacos:
            - "*nacos-server.jar"
          eureka-server:
            - "eureka-server-*.jar"