name: Build Binary

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate App Version
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          DATE=$(date +"%Y%m%d%H%M%S%Z")
          APP_VERSION="${BRANCH_NAME}-${COMMIT_HASH::7}-${DATE}"
          echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
      
      - name: Set up Centos 7 environment
        run: |
          sudo docker pull centos:7
          sudo docker run -v ${{ github.workspace }}:/workspace -w /workspace centos:7 /bin/bash -c "
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* &&
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&
            yum -y update &&
            yum -y install gcc clang llvm make wget curl libbpf-devel &&
            wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz && 
            rm -rf /usr/local/go && 
            tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz &&
            export PATH=$PATH:/usr/local/go/bin &&
            go mod tidy &&
            make build-sdk
            "
      
      - name: Archive Binary
        run: |
          tar -czvf sdk-auto-${{ env.APP_VERSION }}.tar.gz originx-sdk-auto sdk-auto.yml
      
      - name: Upload to OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET: apo-oss
          OSS_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
        run: |
          curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
          sudo ossutil config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET -L CH -c /root/.ossutilconfig
          sudo ossutil cp sdk-auto-${{ env.APP_VERSION }}.tar.gz oss://$OSS_BUCKET/sdk-auto-${{ env.APP_VERSION }}.tar.gz